/**
 * Reveille Cloud — Alert Notification Delivery
 *
 * Supports three channel types:
 *   - teams    : Microsoft Teams Incoming Webhook (POST JSON adaptive card)
 *   - webhook  : Generic HTTP webhook (POST JSON payload)
 *   - email    : Email via Resend API (RESEND_API_KEY) or SMTP (SMTP_HOST/USER/PASS)
 *
 * Called after every alert creation that has a linked alertRule with channels configured.
 */

import type { Alert, AlertRule } from "@shared/schema";

type Channel = { type: string; target: string };

// ---------------------------------------------------------------------------
// Teams Webhook
// ---------------------------------------------------------------------------

async function sendTeamsNotification(webhookUrl: string, alert: Alert): Promise<void> {
  const severityColor =
    alert.severity === "critical" ? "attention" :
    alert.severity === "warning"  ? "warning"   : "accent";

  const card = {
    type: "message",
    attachments: [
      {
        contentType: "application/vnd.microsoft.card.adaptive",
        content: {
          type: "AdaptiveCard",
          version: "1.4",
          body: [
            {
              type: "TextBlock",
              text: `🚨 Reveille Cloud Alert`,
              weight: "bolder",
              size: "medium",
              color: severityColor,
            },
            {
              type: "FactSet",
              facts: [
                { title: "Title",    value: alert.title },
                { title: "Severity", value: alert.severity.toUpperCase() },
                { title: "Time",     value: new Date(alert.timestamp).toUTCString() },
                ...(alert.message ? [{ title: "Details", value: alert.message }] : []),
              ],
            },
          ],
        },
      },
    ],
  };

  const res = await fetch(webhookUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(card),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Teams webhook returned ${res.status}: ${text.slice(0, 200)}`);
  }
}

// ---------------------------------------------------------------------------
// Generic Webhook
// ---------------------------------------------------------------------------

async function sendWebhookNotification(url: string, alert: Alert): Promise<void> {
  const payload = {
    source: "reveille-cloud",
    event: "alert.triggered",
    alert: {
      id: alert.id,
      title: alert.title,
      severity: alert.severity,
      message: alert.message,
      tenantId: alert.tenantId,
      timestamp: alert.timestamp,
    },
  };

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Webhook returned ${res.status}: ${text.slice(0, 200)}`);
  }
}

// ---------------------------------------------------------------------------
// Email (Resend API or SMTP via nodemailer if available)
// ---------------------------------------------------------------------------

async function sendEmailNotification(to: string, alert: Alert): Promise<void> {
  const resendKey = process.env.RESEND_API_KEY;

  const subject = `[Reveille Cloud] ${alert.severity.toUpperCase()}: ${alert.title}`;
  const html = `
    <div style="font-family: sans-serif; max-width: 600px;">
      <h2 style="color: ${alert.severity === 'critical' ? '#dc2626' : '#d97706'}">
        Reveille Cloud Alert — ${alert.severity.toUpperCase()}
      </h2>
      <table style="border-collapse: collapse; width: 100%;">
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Title</td>
            <td style="padding: 6px 12px;">${escapeHtml(alert.title)}</td></tr>
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Severity</td>
            <td style="padding: 6px 12px;">${alert.severity}</td></tr>
        <tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Time</td>
            <td style="padding: 6px 12px;">${new Date(alert.timestamp).toUTCString()}</td></tr>
        ${alert.message ? `<tr><td style="padding: 6px 12px; font-weight: bold; background: #f3f4f6;">Details</td>
            <td style="padding: 6px 12px; white-space: pre-wrap;">${escapeHtml(alert.message)}</td></tr>` : ""}
      </table>
      <p style="margin-top: 16px; font-size: 12px; color: #6b7280;">
        This alert was generated by Reveille Cloud monitoring. Log in to acknowledge or view details.
      </p>
    </div>
  `;

  if (resendKey) {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${resendKey}`,
      },
      body: JSON.stringify({
        from: process.env.RESEND_FROM || "alerts@reveille.cloud",
        to: [to],
        subject,
        html,
      }),
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      throw new Error(`Resend API error: ${body.message || res.statusText}`);
    }
    return;
  }

  // SMTP via nodemailer (optional — only if configured)
  const smtpHost = process.env.SMTP_HOST;
  if (smtpHost) {
    try {
      const nodemailer = await import("nodemailer");
      const transporter = nodemailer.default.createTransport({
        host: smtpHost,
        port: parseInt(process.env.SMTP_PORT || "587"),
        secure: process.env.SMTP_SECURE === "true",
        auth: process.env.SMTP_USER ? {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS || "",
        } : undefined,
      });
      await transporter.sendMail({
        from: process.env.SMTP_FROM || process.env.SMTP_USER || "alerts@reveille.cloud",
        to,
        subject,
        html,
      });
    } catch (err: any) {
      throw new Error(`SMTP send failed: ${err.message}`);
    }
    return;
  }

  // No email transport configured — log the notification
  console.warn(`[Notifications] Email to ${to} not sent — no RESEND_API_KEY or SMTP_HOST configured. Alert: ${alert.title}`);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/**
 * Deliver alert notifications to all channels configured on the alert rule.
 * Fires-and-forgets each channel — errors are logged but do not throw.
 */
export async function deliverAlertNotifications(
  alert: Alert,
  rule: AlertRule | null | undefined
): Promise<void> {
  if (!rule) return;
  const channels = (rule.channels as Channel[]) || [];
  if (channels.length === 0) return;

  for (const channel of channels) {
    try {
      switch (channel.type) {
        case "teams":
          await sendTeamsNotification(channel.target, alert);
          console.log(`[Notifications] Teams notification sent for alert "${alert.title}"`);
          break;
        case "webhook":
          await sendWebhookNotification(channel.target, alert);
          console.log(`[Notifications] Webhook notification sent for alert "${alert.title}"`);
          break;
        case "email":
          await sendEmailNotification(channel.target, alert);
          console.log(`[Notifications] Email notification sent to ${channel.target} for alert "${alert.title}"`);
          break;
        default:
          console.warn(`[Notifications] Unknown channel type "${channel.type}" — skipping`);
      }
    } catch (err: any) {
      console.error(`[Notifications] Failed to deliver ${channel.type} notification for alert "${alert.title}":`, err.message);
    }
  }
}
